[workspace]

[package]
name = "doskrunch-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.doskrunch]
path = ".."

[[bin]]
name = "fuzz_archive_read"
path = "fuzz_targets/fuzz_archive_read.rs"
test = false
doc = false
bench = false
